#!/bin/bash
# 
# Installation script which setup up an Ubuntu Precise machine to use this
# xmonad configuration. 
#
# WARNING!!! 
# * This has only been tested on a limited number of machines running 
#   Ubuntu 12.04 64-bit.
# * This is not a sophisticated installation script by any stretch 
#   of the imagination. 
# * I take no responsibility if this overwrites any configuration settings 
#   or otherwise messes up your system. 
#
# Please review the readme file to find out exactly what it does and does not 
# do. Or, visit the repository for more information: 
# https://github.com/davidbrewer/xmonad-ubuntu-conf
# 
# Author: David Brewer

set -e # Terminate script as soon as any command fails

# colors for pretty output
red_fg=`tput setf 4`
green_fg=`tput setf 2`
bold=`tput bold`
nrml=`tput sgr0`

function tst() {
  # conditionally echo's based on the given commands exit status
  "${@}"
  status=${?}
  if [[ ${status} -ne 0 ]]; then
    echo "${bold}${red_fg}Error executing: ${@}${nrml}"
  else
    echo "${bold}${green_fg}Succesfully executed: ${@}${nrml}"
  fi
}


function install_req_packages() {
  echo "Installing required packages..."
  tst sudo apt-get install -y xmonad libghc-xmonad-dev libghc-xmonad-contrib-dev \
                              xmobar xcompmgr nitrogen stalonetray moreutils \
                              synapse terminator
}

function install_opt_packages() {
  echo "Installing optional packages"
  tst sudo apt-get install -y ssh-askpass-gnome thunar remmina
}

function create_xsess_config() {
  echo "Creating xmonad xsession configuration..."
  if test -e /usr/share/xsessions/xmonad.desktop; then
    echo "Backing up original xmonad.desktop to xmonad.desktop.original"
    tst sudo mv /usr/share/xsessions/xmonad.desktop /usr/share/xsessions/xmonad.desktop.original
  fi
  
  tst sudo cp ~/.xmonad/xmonad.desktop /usr/share/xsessions
  tst sudo cp ~/.xmonad/images/custom_xmonad_badge.png /usr/share/unity-greeter
}

function gnome2_config() {
  echo "Linking to customized gnome 2 configuration..."
  if test -e ~/.gtkrc-2.0; then
    echo "Backing up original .gtkrc-2.0 to gtkrc-2.0.original"
    tst mv ~/.gtkrc-2.0 ~/gtkrc-2.0.original
  fi
  tst ln -s .xmonad/.gtkrc-2.0 ~/.gtkrc-2.0
}

#install_req_packages
#install_opt_packages
#create_xsess_config
#gnome2_config
